[03/May/2017 01:48:19] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 869, in do_for
    " %s" % token.contents)
django.template.base.TemplateSyntaxError: 'for' tag received an invalid argument: for key: value in session.config
[03/May/2017 01:54:26] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'key:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 395, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'key:', expected 'elif', 'else' or 'endif'
[03/May/2017 01:54:44] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'key:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 395, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'key:', expected 'elif', 'else' or 'endif'
[03/May/2017 01:55:25] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python3.6/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python3.6/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 871, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
django.template.base.TemplateSyntaxError: Could not parse the remainder: '()' from 'session.config.iteritems()'
[03/May/2017 01:57:45] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = {key: value for key, value in first_dict.iteritems()}
NameError: name 'first_dict' is not defined
[03/May/2017 01:58:14] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = {key: value for key, value in self.config.iteritems()}
  File "/usr/local/lib/python3.6/site-packages/otree/models/subsession.py", line 52, in __getattribute__
    raise AttributeError(ATTRIBUTE_ERROR_MESSAGE.format(name)) from None
AttributeError: Subsession object has no attribute 'config'. If it is a model field or method,it must be declared on the Subsession class in models.py.
[03/May/2017 01:58:31] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = {key: value for key, value in self.session.config.iteritems()}
AttributeError: 'dict' object has no attribute 'iteritems'
[03/May/2017 01:58:50] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = {key: value for key, value in self.session.config}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in <dictcomp>
    config = {key: value for key, value in self.session.config}
ValueError: too many values to unpack (expected 2)
[03/May/2017 02:04:12] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 126, in vars_for_admin_report
    assert False
AssertionError
[03/May/2017 02:12:35] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = [key, value in self.session.config.items()]
NameError: name 'key' is not defined
[03/May/2017 02:14:58] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 125, in vars_for_admin_report
    config = [key, value in self.session.config.items()]
NameError: name 'key' is not defined
[03/May/2017 02:17:21] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 126, in vars_for_admin_report
    assert False
AssertionError
[03/May/2017 02:20:32] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 126, in vars_for_admin_report
    assert False
AssertionError
[03/May/2017 02:22:49] ERROR [django.request:256] Internal Server Error: /AdminReport/hdi6pntp/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/abstract.py", line 1323, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 670, in get
    context = self.get_context_data(form=form)
  File "/usr/local/lib/python3.6/site-packages/otree/views/admin.py", line 691, in get_context_data
    vars_for_admin_report = subsession.vars_for_admin_report() or {}
  File "/Users/wms5f/Programming/permitauctionsapp/permitauctions/models.py", line 135, in vars_for_admin_report
    'config': config,
NameError: name 'config' is not defined
[03/May/2017 15:51:31] INFO [permitauctionsapp:79] before_session_starts: 48
[03/May/2017 15:51:31] INFO [permitauctionsapp:80] before_session_starts: 24
[03/May/2017 15:53:51] INFO [permitauctionsapp:79] In function: calculate_auction_price
[03/May/2017 15:53:52] INFO [permitauctionsapp:160] ECR range - last_positive_bid_index: 9
[03/May/2017 15:55:39] INFO [permitauctionsapp:79] before_session_starts: 8
[03/May/2017 15:55:39] INFO [permitauctionsapp:80] before_session_starts: 4
[03/May/2017 15:57:36] INFO [permitauctionsapp:79] In function: calculate_auction_price
[03/May/2017 15:57:37] INFO [permitauctionsapp:134] 1st rejected bid - last_positive_bid_index: 9
[03/May/2017 15:57:37] INFO [permitauctionsapp:135] 1st rejected bid - price: 10.00
[03/May/2017 15:57:37] INFO [permitauctionsapp:160] ECR range - last_positive_bid_index: 9
[03/May/2017 15:59:46] INFO [permitauctionsapp:79] In function: calculate_auction_price
[03/May/2017 15:59:46] INFO [permitauctionsapp:134] 1st rejected bid - last_positive_bid_index: 8
[03/May/2017 15:59:46] INFO [permitauctionsapp:135] 1st rejected bid - price: 7.00
[03/May/2017 15:59:46] INFO [permitauctionsapp:160] ECR range - last_positive_bid_index: 8
[03/May/2017 16:12:56] INFO [permitauctionsapp:79] In function: calculate_auction_price
[03/May/2017 16:12:56] INFO [permitauctionsapp:134] 1st rejected bid - last_positive_bid_index: 6
[03/May/2017 16:12:56] INFO [permitauctionsapp:135] 1st rejected bid - price: 6.50
[03/May/2017 16:12:57] INFO [permitauctionsapp:160] ECR range - last_positive_bid_index: 6
[03/May/2017 16:15:18] INFO [permitauctionsapp:79] In function: calculate_auction_price
[03/May/2017 16:15:18] INFO [permitauctionsapp:134] 1st rejected bid - last_positive_bid_index: 6
[03/May/2017 16:15:18] INFO [permitauctionsapp:135] 1st rejected bid - price: 10.50
[03/May/2017 16:15:19] INFO [permitauctionsapp:160] ECR range - last_positive_bid_index: 6
